// Code generated by protoc-gen-go.
// source: azmo.proto
// DO NOT EDIT!

/*
Package azmopb is a generated protocol buffer package.

It is generated from these files:
	azmo.proto

It has these top-level messages:
	BatchRequest
	Argument
	DecrementRequest
	IncrementRequest
	PutRequest
	DeleteRequest
	GetRequest
	RangeRequest
	WatchRequest
	Event
*/
package azmopb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event_Type int32

const (
	Event_DECREMENT Event_Type = 0
	Event_INCREMENT Event_Type = 1
	Event_PUT       Event_Type = 2
	Event_DELETE    Event_Type = 3
	Event_GET       Event_Type = 4
	Event_RANGE     Event_Type = 5
	Event_WATCH     Event_Type = 6
)

var Event_Type_name = map[int32]string{
	0: "DECREMENT",
	1: "INCREMENT",
	2: "PUT",
	3: "DELETE",
	4: "GET",
	5: "RANGE",
	6: "WATCH",
}
var Event_Type_value = map[string]int32{
	"DECREMENT": 0,
	"INCREMENT": 1,
	"PUT":       2,
	"DELETE":    3,
	"GET":       4,
	"RANGE":     5,
	"WATCH":     6,
}

func (x Event_Type) String() string {
	return proto.EnumName(Event_Type_name, int32(x))
}
func (Event_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

type BatchRequest struct {
	Arguments []*Argument `protobuf:"bytes,1,rep,name=arguments" json:"arguments,omitempty"`
}

func (m *BatchRequest) Reset()                    { *m = BatchRequest{} }
func (m *BatchRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchRequest) ProtoMessage()               {}
func (*BatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BatchRequest) GetArguments() []*Argument {
	if m != nil {
		return m.Arguments
	}
	return nil
}

type Argument struct {
	// Types that are valid to be assigned to Command:
	//	*Argument_Decrement
	//	*Argument_Increment
	//	*Argument_Put
	//	*Argument_Delete
	Command isArgument_Command `protobuf_oneof:"Command"`
}

func (m *Argument) Reset()                    { *m = Argument{} }
func (m *Argument) String() string            { return proto.CompactTextString(m) }
func (*Argument) ProtoMessage()               {}
func (*Argument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isArgument_Command interface {
	isArgument_Command()
}

type Argument_Decrement struct {
	Decrement *DecrementRequest `protobuf:"bytes,1,opt,name=decrement,oneof"`
}
type Argument_Increment struct {
	Increment *IncrementRequest `protobuf:"bytes,2,opt,name=increment,oneof"`
}
type Argument_Put struct {
	Put *PutRequest `protobuf:"bytes,3,opt,name=put,oneof"`
}
type Argument_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,4,opt,name=delete,oneof"`
}

func (*Argument_Decrement) isArgument_Command() {}
func (*Argument_Increment) isArgument_Command() {}
func (*Argument_Put) isArgument_Command()       {}
func (*Argument_Delete) isArgument_Command()    {}

func (m *Argument) GetCommand() isArgument_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Argument) GetDecrement() *DecrementRequest {
	if x, ok := m.GetCommand().(*Argument_Decrement); ok {
		return x.Decrement
	}
	return nil
}

func (m *Argument) GetIncrement() *IncrementRequest {
	if x, ok := m.GetCommand().(*Argument_Increment); ok {
		return x.Increment
	}
	return nil
}

func (m *Argument) GetPut() *PutRequest {
	if x, ok := m.GetCommand().(*Argument_Put); ok {
		return x.Put
	}
	return nil
}

func (m *Argument) GetDelete() *DeleteRequest {
	if x, ok := m.GetCommand().(*Argument_Delete); ok {
		return x.Delete
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Argument) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Argument_OneofMarshaler, _Argument_OneofUnmarshaler, _Argument_OneofSizer, []interface{}{
		(*Argument_Decrement)(nil),
		(*Argument_Increment)(nil),
		(*Argument_Put)(nil),
		(*Argument_Delete)(nil),
	}
}

func _Argument_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Argument)
	// Command
	switch x := m.Command.(type) {
	case *Argument_Decrement:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Decrement); err != nil {
			return err
		}
	case *Argument_Increment:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Increment); err != nil {
			return err
		}
	case *Argument_Put:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case *Argument_Delete:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Delete); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Argument.Command has unexpected type %T", x)
	}
	return nil
}

func _Argument_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Argument)
	switch tag {
	case 1: // Command.decrement
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DecrementRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Argument_Decrement{msg}
		return true, err
	case 2: // Command.increment
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(IncrementRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Argument_Increment{msg}
		return true, err
	case 3: // Command.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Argument_Put{msg}
		return true, err
	case 4: // Command.delete
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeleteRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Argument_Delete{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Argument_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Argument)
	// Command
	switch x := m.Command.(type) {
	case *Argument_Decrement:
		s := proto.Size(x.Decrement)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Argument_Increment:
		s := proto.Size(x.Increment)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Argument_Put:
		s := proto.Size(x.Put)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Argument_Delete:
		s := proto.Size(x.Delete)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DecrementRequest struct {
	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Tombstone bool   `protobuf:"varint,3,opt,name=tombstone" json:"tombstone,omitempty"`
}

func (m *DecrementRequest) Reset()                    { *m = DecrementRequest{} }
func (m *DecrementRequest) String() string            { return proto.CompactTextString(m) }
func (*DecrementRequest) ProtoMessage()               {}
func (*DecrementRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DecrementRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DecrementRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *DecrementRequest) GetTombstone() bool {
	if m != nil {
		return m.Tombstone
	}
	return false
}

type IncrementRequest struct {
	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Tombstone bool   `protobuf:"varint,3,opt,name=tombstone" json:"tombstone,omitempty"`
}

func (m *IncrementRequest) Reset()                    { *m = IncrementRequest{} }
func (m *IncrementRequest) String() string            { return proto.CompactTextString(m) }
func (*IncrementRequest) ProtoMessage()               {}
func (*IncrementRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IncrementRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *IncrementRequest) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *IncrementRequest) GetTombstone() bool {
	if m != nil {
		return m.Tombstone
	}
	return false
}

type PutRequest struct {
	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Tombstone bool   `protobuf:"varint,3,opt,name=tombstone" json:"tombstone,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PutRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *PutRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *PutRequest) GetTombstone() bool {
	if m != nil {
		return m.Tombstone
	}
	return false
}

type DeleteRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type GetRequest struct {
	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Revision  int64  `protobuf:"varint,2,opt,name=revision" json:"revision,omitempty"`
	MustEqual bool   `protobuf:"varint,3,opt,name=must_equal,json=mustEqual" json:"must_equal,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *GetRequest) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *GetRequest) GetMustEqual() bool {
	if m != nil {
		return m.MustEqual
	}
	return false
}

type RangeRequest struct {
	From     []byte `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To       []byte `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Revision int64  `protobuf:"varint,3,opt,name=revision" json:"revision,omitempty"`
	Limit    int32  `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
}

func (m *RangeRequest) Reset()                    { *m = RangeRequest{} }
func (m *RangeRequest) String() string            { return proto.CompactTextString(m) }
func (*RangeRequest) ProtoMessage()               {}
func (*RangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RangeRequest) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *RangeRequest) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *RangeRequest) GetRevision() int64 {
	if m != nil {
		return m.Revision
	}
	return 0
}

func (m *RangeRequest) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type WatchRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *WatchRequest) Reset()                    { *m = WatchRequest{} }
func (m *WatchRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()               {}
func (*WatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *WatchRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type Event struct {
	Type    Event_Type `protobuf:"varint,1,opt,name=type,enum=db.Event_Type" json:"type,omitempty"`
	Content []byte     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Numeric int64      `protobuf:"varint,3,opt,name=numeric" json:"numeric,omitempty"`
	Key     []byte     `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Created int64      `protobuf:"varint,5,opt,name=created" json:"created,omitempty"`
	Current int64      `protobuf:"varint,6,opt,name=current" json:"current,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Event) GetType() Event_Type {
	if m != nil {
		return m.Type
	}
	return Event_DECREMENT
}

func (m *Event) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Event) GetNumeric() int64 {
	if m != nil {
		return m.Numeric
	}
	return 0
}

func (m *Event) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Event) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Event) GetCurrent() int64 {
	if m != nil {
		return m.Current
	}
	return 0
}

func init() {
	proto.RegisterType((*BatchRequest)(nil), "db.BatchRequest")
	proto.RegisterType((*Argument)(nil), "db.Argument")
	proto.RegisterType((*DecrementRequest)(nil), "db.DecrementRequest")
	proto.RegisterType((*IncrementRequest)(nil), "db.IncrementRequest")
	proto.RegisterType((*PutRequest)(nil), "db.PutRequest")
	proto.RegisterType((*DeleteRequest)(nil), "db.DeleteRequest")
	proto.RegisterType((*GetRequest)(nil), "db.GetRequest")
	proto.RegisterType((*RangeRequest)(nil), "db.RangeRequest")
	proto.RegisterType((*WatchRequest)(nil), "db.WatchRequest")
	proto.RegisterType((*Event)(nil), "db.Event")
	proto.RegisterEnum("db.Event_Type", Event_Type_name, Event_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DB service

type DBClient interface {
	Decrement(ctx context.Context, in *DecrementRequest, opts ...grpc.CallOption) (*Event, error)
	Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*Event, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Event, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Event, error)
	Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (DB_BatchClient, error)
	Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (DB_RangeClient, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Event, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (DB_WatchClient, error)
}

type dBClient struct {
	cc *grpc.ClientConn
}

func NewDBClient(cc *grpc.ClientConn) DBClient {
	return &dBClient{cc}
}

func (c *dBClient) Decrement(ctx context.Context, in *DecrementRequest, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := grpc.Invoke(ctx, "/db.DB/Decrement", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := grpc.Invoke(ctx, "/db.DB/Increment", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := grpc.Invoke(ctx, "/db.DB/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := grpc.Invoke(ctx, "/db.DB/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (DB_BatchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DB_serviceDesc.Streams[0], c.cc, "/db.DB/Batch", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBBatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DB_BatchClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type dBBatchClient struct {
	grpc.ClientStream
}

func (x *dBBatchClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBClient) Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (DB_RangeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DB_serviceDesc.Streams[1], c.cc, "/db.DB/Range", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBRangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DB_RangeClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type dBRangeClient struct {
	grpc.ClientStream
}

func (x *dBRangeClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := grpc.Invoke(ctx, "/db.DB/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (DB_WatchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DB_serviceDesc.Streams[2], c.cc, "/db.DB/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DB_WatchClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type dBWatchClient struct {
	grpc.ClientStream
}

func (x *dBWatchClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for DB service

type DBServer interface {
	Decrement(context.Context, *DecrementRequest) (*Event, error)
	Increment(context.Context, *IncrementRequest) (*Event, error)
	Put(context.Context, *PutRequest) (*Event, error)
	Delete(context.Context, *DeleteRequest) (*Event, error)
	Batch(*BatchRequest, DB_BatchServer) error
	Range(*RangeRequest, DB_RangeServer) error
	Get(context.Context, *GetRequest) (*Event, error)
	Watch(*WatchRequest, DB_WatchServer) error
}

func RegisterDBServer(s *grpc.Server, srv DBServer) {
	s.RegisterService(&_DB_serviceDesc, srv)
}

func _DB_Decrement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Decrement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DB/Decrement",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Decrement(ctx, req.(*DecrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DB/Increment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Increment(ctx, req.(*IncrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DB/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DB/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Batch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DBServer).Batch(m, &dBBatchServer{stream})
}

type DB_BatchServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type dBBatchServer struct {
	grpc.ServerStream
}

func (x *dBBatchServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _DB_Range_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DBServer).Range(m, &dBRangeServer{stream})
}

type DB_RangeServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type dBRangeServer struct {
	grpc.ServerStream
}

func (x *dBRangeServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _DB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/db.DB/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DBServer).Watch(m, &dBWatchServer{stream})
}

type DB_WatchServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type dBWatchServer struct {
	grpc.ServerStream
}

func (x *dBWatchServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _DB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "db.DB",
	HandlerType: (*DBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decrement",
			Handler:    _DB_Decrement_Handler,
		},
		{
			MethodName: "Increment",
			Handler:    _DB_Increment_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _DB_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DB_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DB_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Batch",
			Handler:       _DB_Batch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Range",
			Handler:       _DB_Range_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _DB_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "azmo.proto",
}

func init() { proto.RegisterFile("azmo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xcb, 0x8e, 0xd3, 0x4a,
	0x10, 0x1d, 0x3f, 0x13, 0xd7, 0x78, 0x22, 0xdf, 0x52, 0x16, 0xd6, 0xe8, 0x22, 0x05, 0x2f, 0xd0,
	0x08, 0x50, 0x84, 0x02, 0x2b, 0x76, 0x79, 0x58, 0x99, 0x91, 0x20, 0x8a, 0x5a, 0x46, 0x19, 0xd8,
	0x20, 0x27, 0x6e, 0x06, 0x8b, 0xd8, 0xce, 0x38, 0xed, 0x48, 0xe1, 0xfb, 0xf8, 0x02, 0x7e, 0x08,
	0xd4, 0xed, 0x67, 0x92, 0xe1, 0xb1, 0x60, 0xd7, 0xa7, 0xea, 0x74, 0x9d, 0xaa, 0xd6, 0xa9, 0x06,
	0xf0, 0xbf, 0x46, 0x49, 0x7f, 0x93, 0x26, 0x2c, 0x41, 0x39, 0x58, 0x3a, 0xaf, 0xc1, 0x1c, 0xf9,
	0x6c, 0xf5, 0x99, 0xd0, 0xfb, 0x8c, 0x6e, 0x19, 0x3e, 0x05, 0xc3, 0x4f, 0xef, 0xb2, 0x88, 0xc6,
	0x6c, 0x6b, 0x4b, 0x3d, 0xe5, 0xea, 0x7c, 0x60, 0xf6, 0x83, 0x65, 0x7f, 0x58, 0x04, 0x49, 0x9d,
	0x76, 0xbe, 0x4b, 0xd0, 0x2e, 0xe3, 0xf8, 0x0a, 0x8c, 0x80, 0xae, 0x52, 0xca, 0x81, 0x2d, 0xf5,
	0xa4, 0xab, 0xf3, 0x41, 0x97, 0x5f, 0x9c, 0x94, 0xc1, 0x42, 0xe1, 0xfa, 0x8c, 0xd4, 0x44, 0x7e,
	0x2b, 0x8c, 0xcb, 0x5b, 0x72, 0x7d, 0xeb, 0x26, 0x3e, 0xbd, 0x55, 0x11, 0xd1, 0x01, 0x65, 0x93,
	0x31, 0x5b, 0x11, 0xfc, 0x0e, 0xe7, 0xcf, 0xb3, 0x06, 0x93, 0x27, 0xf1, 0x19, 0xe8, 0x01, 0x5d,
	0x53, 0x46, 0x6d, 0x55, 0xd0, 0xfe, 0xcb, 0x9b, 0xe1, 0x91, 0x9a, 0x59, 0x50, 0x46, 0x06, 0xb4,
	0xc6, 0x49, 0x14, 0xf9, 0x71, 0xe0, 0xdc, 0x82, 0x75, 0xdc, 0x32, 0x5a, 0xa0, 0x7c, 0xa1, 0x7b,
	0x31, 0x95, 0x49, 0xf8, 0x11, 0xbb, 0xa0, 0xed, 0xfc, 0x75, 0x46, 0x45, 0xcf, 0x0a, 0xc9, 0x01,
	0xfe, 0x0f, 0x06, 0x4b, 0xa2, 0xe5, 0x96, 0x25, 0x31, 0x15, 0xdd, 0xb5, 0x49, 0x1d, 0xe0, 0x95,
	0x8f, 0xc7, 0xfa, 0x47, 0x95, 0x09, 0x40, 0xfd, 0x00, 0x7f, 0xaa, 0x69, 0xfe, 0x5d, 0xcd, 0xc7,
	0x70, 0x71, 0xf0, 0x5a, 0xa7, 0x65, 0x9d, 0xf7, 0x00, 0x53, 0xfa, 0x1b, 0xd9, 0x4b, 0x68, 0xa7,
	0x74, 0x17, 0x6e, 0xc3, 0x24, 0x2e, 0xa6, 0xa9, 0x30, 0x3e, 0x02, 0x88, 0xb2, 0x2d, 0xfb, 0x48,
	0xef, 0x33, 0x7f, 0x5d, 0xaa, 0xf3, 0x88, 0xcb, 0x03, 0x4e, 0x00, 0x26, 0xf1, 0xe3, 0xbb, 0x4a,
	0x1c, 0x41, 0xfd, 0x94, 0x26, 0x51, 0x51, 0x5d, 0x9c, 0xb1, 0x03, 0x32, 0x4b, 0x8a, 0x91, 0x64,
	0x96, 0x1c, 0xc8, 0x29, 0x47, 0x72, 0x5d, 0xd0, 0xd6, 0x61, 0x14, 0x32, 0x61, 0x06, 0x8d, 0xe4,
	0xc0, 0xe9, 0x81, 0xb9, 0x68, 0x9a, 0xff, 0x74, 0xc4, 0x1f, 0x12, 0x68, 0xee, 0x2e, 0xf7, 0x9c,
	0xca, 0xf6, 0x1b, 0x2a, 0x92, 0x9d, 0xdc, 0x74, 0x22, 0xd1, 0xf7, 0xf6, 0x1b, 0x4a, 0x44, 0x0e,
	0x6d, 0x68, 0xad, 0x92, 0x98, 0x95, 0x5e, 0x36, 0x49, 0x09, 0x79, 0x26, 0xce, 0x22, 0x9a, 0x86,
	0xab, 0xa2, 0xb5, 0x12, 0x96, 0x9a, 0x6a, 0xfd, 0x6c, 0xbc, 0x4a, 0x4a, 0x7d, 0x46, 0x03, 0x5b,
	0xcb, 0xb9, 0x05, 0x14, 0x99, 0x2c, 0x4d, 0x79, 0x7d, 0xbd, 0xc8, 0xe4, 0xd0, 0xb9, 0x05, 0x95,
	0xf7, 0x81, 0x17, 0x60, 0x4c, 0xdc, 0x31, 0x71, 0xdf, 0xba, 0x33, 0xcf, 0x3a, 0xe3, 0xf0, 0x66,
	0x56, 0x42, 0x09, 0x5b, 0xa0, 0xcc, 0xdf, 0x79, 0x96, 0x8c, 0x00, 0xfa, 0xc4, 0x7d, 0xe3, 0x7a,
	0xae, 0xa5, 0xf0, 0xe0, 0xd4, 0xf5, 0x2c, 0x15, 0x0d, 0xd0, 0xc8, 0x70, 0x36, 0x75, 0x2d, 0x8d,
	0x1f, 0x17, 0x43, 0x6f, 0x7c, 0x6d, 0xe9, 0x83, 0x6f, 0x32, 0xc8, 0x93, 0x11, 0x3e, 0x07, 0xa3,
	0x5a, 0x0b, 0x7c, 0x70, 0xb1, 0x2f, 0x8d, 0xea, 0x4d, 0x38, 0xbb, 0xb2, 0x3a, 0x3e, 0xb8, 0xd0,
	0x4d, 0x76, 0x0f, 0x94, 0x79, 0xc6, 0xf0, 0x68, 0x91, 0x9b, 0x8c, 0x27, 0xa0, 0xe7, 0x66, 0xc4,
	0xd3, 0x35, 0x3e, 0xe4, 0x69, 0xe2, 0x37, 0x43, 0x8b, 0xc7, 0x9a, 0x1f, 0x5b, 0x83, 0xf5, 0x42,
	0xe2, 0x3c, 0x61, 0xaf, 0x9c, 0xd7, 0x74, 0xda, 0x21, 0xaf, 0x07, 0xca, 0x94, 0x16, 0x9d, 0xd5,
	0x56, 0x3f, 0x52, 0x5c, 0xd4, 0x8a, 0x8b, 0x5f, 0x29, 0x8e, 0xda, 0x1f, 0x74, 0xfe, 0xf3, 0x6e,
	0x96, 0x4b, 0x5d, 0x7c, 0xbe, 0x2f, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe6, 0x66, 0x42, 0x38,
	0x8a, 0x05, 0x00, 0x00,
}
