// Code generated by protoc-gen-go.
// source: test.proto
// DO NOT EDIT!

/*
Package googlepb is a generated protocol buffer package.

It is generated from these files:
	test.proto

It has these top-level messages:
	Message
*/
package googlepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Message struct {
	Arg1 string `protobuf:"bytes,1,opt,name=arg1" json:"arg1,omitempty"`
	Arg2 uint64 `protobuf:"varint,2,opt,name=arg2" json:"arg2,omitempty"`
	Arg3 uint32 `protobuf:"varint,3,opt,name=arg3" json:"arg3,omitempty"`
	Arg4 []byte `protobuf:"bytes,4,opt,name=arg4,proto3" json:"arg4,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetArg1() string {
	if m != nil {
		return m.Arg1
	}
	return ""
}

func (m *Message) GetArg2() uint64 {
	if m != nil {
		return m.Arg2
	}
	return 0
}

func (m *Message) GetArg3() uint32 {
	if m != nil {
		return m.Arg3
	}
	return 0
}

func (m *Message) GetArg4() []byte {
	if m != nil {
		return m.Arg4
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "googlepb.Message")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x48, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0x2d, 0x48,
	0x52, 0x8a, 0xe4, 0x62, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x15, 0x12, 0xe2, 0x62, 0x49,
	0x2c, 0x4a, 0x37, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0xa1, 0x62, 0x46, 0x12,
	0x4c, 0x0a, 0x8c, 0x1a, 0x2c, 0x60, 0x31, 0x23, 0xa8, 0x98, 0xb1, 0x04, 0xb3, 0x02, 0xa3, 0x06,
	0x2f, 0x58, 0xcc, 0x18, 0x2a, 0x66, 0x22, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x03, 0x16, 0x33, 0x49,
	0x62, 0x03, 0xdb, 0x65, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x44, 0xd8, 0xa0, 0x99, 0x79, 0x00,
	0x00, 0x00,
}
