// Code generated by protoc-gen-go.
// source: azmo.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	azmo.proto

It has these top-level messages:
	BatchRequest
	Argument
	DeleteRequest
	PutRequest
	NumericRequest
	RangeRequest
	GetRequest
	WatchRequest
	Event
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import db "github.com/azmodb/db/pb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BatchRequest struct {
	Args []*Argument `protobuf:"bytes,1,rep,name=args" json:"args,omitempty"`
}

func (m *BatchRequest) Reset()                    { *m = BatchRequest{} }
func (m *BatchRequest) String() string            { return proto.CompactTextString(m) }
func (*BatchRequest) ProtoMessage()               {}
func (*BatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BatchRequest) GetArgs() []*Argument {
	if m != nil {
		return m.Args
	}
	return nil
}

type Argument struct {
	// Types that are valid to be assigned to Command:
	//	*Argument_Increment
	//	*Argument_Decrement
	//	*Argument_Delete
	//	*Argument_Put
	Command isArgument_Command `protobuf_oneof:"Command"`
}

func (m *Argument) Reset()                    { *m = Argument{} }
func (m *Argument) String() string            { return proto.CompactTextString(m) }
func (*Argument) ProtoMessage()               {}
func (*Argument) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type isArgument_Command interface {
	isArgument_Command()
}

type Argument_Increment struct {
	Increment *NumericRequest `protobuf:"bytes,1,opt,name=increment,oneof"`
}
type Argument_Decrement struct {
	Decrement *NumericRequest `protobuf:"bytes,2,opt,name=decrement,oneof"`
}
type Argument_Delete struct {
	Delete *DeleteRequest `protobuf:"bytes,3,opt,name=delete,oneof"`
}
type Argument_Put struct {
	Put *PutRequest `protobuf:"bytes,4,opt,name=put,oneof"`
}

func (*Argument_Increment) isArgument_Command() {}
func (*Argument_Decrement) isArgument_Command() {}
func (*Argument_Delete) isArgument_Command()    {}
func (*Argument_Put) isArgument_Command()       {}

func (m *Argument) GetCommand() isArgument_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Argument) GetIncrement() *NumericRequest {
	if x, ok := m.GetCommand().(*Argument_Increment); ok {
		return x.Increment
	}
	return nil
}

func (m *Argument) GetDecrement() *NumericRequest {
	if x, ok := m.GetCommand().(*Argument_Decrement); ok {
		return x.Decrement
	}
	return nil
}

func (m *Argument) GetDelete() *DeleteRequest {
	if x, ok := m.GetCommand().(*Argument_Delete); ok {
		return x.Delete
	}
	return nil
}

func (m *Argument) GetPut() *PutRequest {
	if x, ok := m.GetCommand().(*Argument_Put); ok {
		return x.Put
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Argument) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Argument_OneofMarshaler, _Argument_OneofUnmarshaler, _Argument_OneofSizer, []interface{}{
		(*Argument_Increment)(nil),
		(*Argument_Decrement)(nil),
		(*Argument_Delete)(nil),
		(*Argument_Put)(nil),
	}
}

func _Argument_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Argument)
	// Command
	switch x := m.Command.(type) {
	case *Argument_Increment:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Increment); err != nil {
			return err
		}
	case *Argument_Decrement:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Decrement); err != nil {
			return err
		}
	case *Argument_Delete:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Delete); err != nil {
			return err
		}
	case *Argument_Put:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Put); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Argument.Command has unexpected type %T", x)
	}
	return nil
}

func _Argument_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Argument)
	switch tag {
	case 1: // Command.increment
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NumericRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Argument_Increment{msg}
		return true, err
	case 2: // Command.decrement
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(NumericRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Argument_Decrement{msg}
		return true, err
	case 3: // Command.delete
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DeleteRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Argument_Delete{msg}
		return true, err
	case 4: // Command.put
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PutRequest)
		err := b.DecodeMessage(msg)
		m.Command = &Argument_Put{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Argument_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Argument)
	// Command
	switch x := m.Command.(type) {
	case *Argument_Increment:
		s := proto.Size(x.Increment)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Argument_Decrement:
		s := proto.Size(x.Decrement)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Argument_Delete:
		s := proto.Size(x.Delete)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Argument_Put:
		s := proto.Size(x.Put)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DeleteRequest struct {
	Key  []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Prev bool   `protobuf:"varint,2,opt,name=prev" json:"prev,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type PutRequest struct {
	Key       []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value     []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Prev      bool   `protobuf:"varint,3,opt,name=prev" json:"prev,omitempty"`
	Tombstone bool   `protobuf:"varint,4,opt,name=tombstone" json:"tombstone,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type NumericRequest struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value int64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Prev  bool   `protobuf:"varint,3,opt,name=prev" json:"prev,omitempty"`
}

func (m *NumericRequest) Reset()                    { *m = NumericRequest{} }
func (m *NumericRequest) String() string            { return proto.CompactTextString(m) }
func (*NumericRequest) ProtoMessage()               {}
func (*NumericRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type RangeRequest struct {
	From     []byte `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To       []byte `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Rev      int64  `protobuf:"varint,3,opt,name=rev" json:"rev,omitempty"`
	Versions bool   `protobuf:"varint,4,opt,name=versions" json:"versions,omitempty"`
}

func (m *RangeRequest) Reset()                    { *m = RangeRequest{} }
func (m *RangeRequest) String() string            { return proto.CompactTextString(m) }
func (*RangeRequest) ProtoMessage()               {}
func (*RangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type GetRequest struct {
	Key      []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Rev      int64  `protobuf:"varint,3,opt,name=rev" json:"rev,omitempty"`
	Versions bool   `protobuf:"varint,4,opt,name=versions" json:"versions,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type WatchRequest struct {
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *WatchRequest) Reset()                    { *m = WatchRequest{} }
func (m *WatchRequest) String() string            { return proto.CompactTextString(m) }
func (*WatchRequest) ProtoMessage()               {}
func (*WatchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Event struct {
	Record *db.Record `protobuf:"bytes,1,opt,name=record" json:"record,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Event) GetRecord() *db.Record {
	if m != nil {
		return m.Record
	}
	return nil
}

func init() {
	proto.RegisterType((*BatchRequest)(nil), "azmo.BatchRequest")
	proto.RegisterType((*Argument)(nil), "azmo.Argument")
	proto.RegisterType((*DeleteRequest)(nil), "azmo.DeleteRequest")
	proto.RegisterType((*PutRequest)(nil), "azmo.PutRequest")
	proto.RegisterType((*NumericRequest)(nil), "azmo.NumericRequest")
	proto.RegisterType((*RangeRequest)(nil), "azmo.RangeRequest")
	proto.RegisterType((*GetRequest)(nil), "azmo.GetRequest")
	proto.RegisterType((*WatchRequest)(nil), "azmo.WatchRequest")
	proto.RegisterType((*Event)(nil), "azmo.Event")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for DB service

type DBClient interface {
	Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (DB_RangeClient, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Event, error)
	Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (DB_WatchClient, error)
	Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (DB_BatchClient, error)
}

type dBClient struct {
	cc *grpc.ClientConn
}

func NewDBClient(cc *grpc.ClientConn) DBClient {
	return &dBClient{cc}
}

func (c *dBClient) Range(ctx context.Context, in *RangeRequest, opts ...grpc.CallOption) (DB_RangeClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DB_serviceDesc.Streams[0], c.cc, "/azmo.DB/Range", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBRangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DB_RangeClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type dBRangeClient struct {
	grpc.ClientStream
}

func (x *dBRangeClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Event, error) {
	out := new(Event)
	err := grpc.Invoke(ctx, "/azmo.DB/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Watch(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (DB_WatchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DB_serviceDesc.Streams[1], c.cc, "/azmo.DB/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DB_WatchClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type dBWatchClient struct {
	grpc.ClientStream
}

func (x *dBWatchClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dBClient) Batch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (DB_BatchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_DB_serviceDesc.Streams[2], c.cc, "/azmo.DB/Batch", opts...)
	if err != nil {
		return nil, err
	}
	x := &dBBatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type DB_BatchClient interface {
	Recv() (*Event, error)
	grpc.ClientStream
}

type dBBatchClient struct {
	grpc.ClientStream
}

func (x *dBBatchClient) Recv() (*Event, error) {
	m := new(Event)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for DB service

type DBServer interface {
	Range(*RangeRequest, DB_RangeServer) error
	Get(context.Context, *GetRequest) (*Event, error)
	Watch(*WatchRequest, DB_WatchServer) error
	Batch(*BatchRequest, DB_BatchServer) error
}

func RegisterDBServer(s *grpc.Server, srv DBServer) {
	s.RegisterService(&_DB_serviceDesc, srv)
}

func _DB_Range_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DBServer).Range(m, &dBRangeServer{stream})
}

type DB_RangeServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type dBRangeServer struct {
	grpc.ServerStream
}

func (x *dBRangeServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _DB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/azmo.DB/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DB_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DBServer).Watch(m, &dBWatchServer{stream})
}

type DB_WatchServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type dBWatchServer struct {
	grpc.ServerStream
}

func (x *dBWatchServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

func _DB_Batch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DBServer).Batch(m, &dBBatchServer{stream})
}

type DB_BatchServer interface {
	Send(*Event) error
	grpc.ServerStream
}

type dBBatchServer struct {
	grpc.ServerStream
}

func (x *dBBatchServer) Send(m *Event) error {
	return x.ServerStream.SendMsg(m)
}

var _DB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "azmo.DB",
	HandlerType: (*DBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _DB_Get_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Range",
			Handler:       _DB_Range_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Watch",
			Handler:       _DB_Watch_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Batch",
			Handler:       _DB_Batch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("azmo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 452 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x93, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xc7, 0x49, 0x93, 0x96, 0x76, 0x36, 0x54, 0x2b, 0xb3, 0x87, 0xaa, 0xe2, 0x50, 0x59, 0x1c,
	0x10, 0x88, 0x2c, 0x2a, 0xf0, 0x00, 0x84, 0x45, 0x70, 0x40, 0x08, 0xf9, 0x82, 0xc4, 0x89, 0x7c,
	0x78, 0xb3, 0x11, 0x4d, 0x1c, 0x1c, 0x27, 0x12, 0x3c, 0x14, 0x8f, 0xc3, 0xf3, 0x60, 0x4f, 0x9c,
	0x8f, 0xf2, 0x51, 0x84, 0x54, 0x55, 0xe3, 0xf1, 0xff, 0xff, 0xf3, 0xcc, 0x68, 0x02, 0x10, 0x7d,
	0x2b, 0x44, 0x50, 0x49, 0xa1, 0x04, 0xf1, 0x4c, 0xbc, 0xdd, 0x65, 0xb9, 0xba, 0x69, 0xe2, 0x20,
	0x11, 0xc5, 0xa5, 0x49, 0xa4, 0xf1, 0xa5, 0xfe, 0x55, 0xe6, 0xbf, 0xd3, 0xd1, 0x3d, 0xf8, 0x61,
	0xa4, 0x92, 0x1b, 0xc6, 0xbf, 0x34, 0xbc, 0x56, 0x84, 0x82, 0x17, 0xc9, 0xac, 0xde, 0x38, 0x3b,
	0xf7, 0xc1, 0xd9, 0x7e, 0x1d, 0x20, 0xf2, 0x85, 0xcc, 0x9a, 0x82, 0x97, 0x8a, 0xe1, 0x1d, 0xfd,
	0xe1, 0xc0, 0xb2, 0x4f, 0x91, 0x67, 0xb0, 0xca, 0xcb, 0x44, 0x72, 0x73, 0xd0, 0x2e, 0x47, 0xbb,
	0x2e, 0x3a, 0xd7, 0x3b, 0x2d, 0x90, 0x79, 0x62, 0xc9, 0x6f, 0x6e, 0xb1, 0x51, 0x68, 0x5c, 0x29,
	0xef, 0x5d, 0xb3, 0xd3, 0xae, 0x41, 0x48, 0x1e, 0xc3, 0x22, 0xe5, 0x07, 0xae, 0xf8, 0xc6, 0x45,
	0xcb, 0xdd, 0xce, 0x72, 0x85, 0xb9, 0xd1, 0x61, 0x45, 0xe4, 0x3e, 0xb8, 0x55, 0xa3, 0x36, 0x1e,
	0x6a, 0xcf, 0x3b, 0xed, 0xfb, 0x46, 0x8d, 0x42, 0x73, 0x1d, 0xae, 0xe0, 0xf6, 0x4b, 0x51, 0x14,
	0x51, 0x99, 0xd2, 0xe7, 0x70, 0xe7, 0x88, 0x45, 0xce, 0xc1, 0xfd, 0xcc, 0xbf, 0x62, 0x5b, 0x3e,
	0x33, 0x21, 0x21, 0xe0, 0x55, 0x92, 0xb7, 0x58, 0xf3, 0x92, 0x61, 0x4c, 0xaf, 0x01, 0x46, 0xec,
	0x1f, 0x3c, 0x17, 0x30, 0x6f, 0xa3, 0x43, 0xc3, 0xd1, 0xe4, 0xb3, 0xee, 0x30, 0x90, 0xdc, 0x91,
	0x44, 0xee, 0xc1, 0x4a, 0x89, 0x22, 0xae, 0x95, 0x28, 0x39, 0xd6, 0xbd, 0x64, 0x63, 0x82, 0xbe,
	0x85, 0xf5, 0xf1, 0x74, 0xfe, 0xf5, 0x96, 0x7b, 0xe2, 0x2d, 0xfa, 0x09, 0x7c, 0x16, 0x95, 0xd9,
	0xd0, 0xab, 0xd6, 0x5c, 0x4b, 0x51, 0x58, 0x18, 0xc6, 0x64, 0x0d, 0x33, 0x25, 0x6c, 0xd9, 0x3a,
	0x32, 0xef, 0xf5, 0x18, 0x97, 0x99, 0x90, 0x6c, 0x61, 0xd9, 0x72, 0x59, 0xe7, 0xa2, 0xac, 0x6d,
	0xc1, 0xc3, 0x59, 0xd7, 0x0b, 0xaf, 0xf9, 0x89, 0xb9, 0xfc, 0x1f, 0x6d, 0x07, 0xfe, 0x87, 0xe9,
	0xa6, 0xfe, 0xc6, 0xa3, 0x8f, 0x60, 0xfe, 0xaa, 0x35, 0x7b, 0x42, 0x61, 0x21, 0x79, 0x22, 0x64,
	0x6a, 0x17, 0x12, 0x02, 0xbd, 0xef, 0x0c, 0x33, 0xcc, 0xde, 0xec, 0xbf, 0x3b, 0x30, 0xbb, 0x0a,
	0xc9, 0x43, 0x98, 0xe3, 0x14, 0x08, 0xe9, 0xf6, 0x63, 0x3a, 0x92, 0xed, 0x59, 0x97, 0x43, 0xe8,
	0x13, 0xc7, 0xec, 0x93, 0xee, 0x87, 0xd8, 0x4d, 0x1a, 0x5b, 0x3b, 0xd2, 0x19, 0x22, 0xd6, 0xd9,
	0x13, 0xa7, 0x45, 0xff, 0x4a, 0xd4, 0xda, 0x70, 0xaa, 0x0d, 0xff, 0xae, 0x0d, 0xbd, 0x8f, 0xb3,
	0x2a, 0x8e, 0x17, 0xf8, 0xd9, 0x3e, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0x78, 0x40, 0x78, 0xe4,
	0xec, 0x03, 0x00, 0x00,
}
